.TH "funcs.cpp" 3 "Sun Aug 28 2022" "Version 2" "String operations.com" \" -*- nroff -*-
.ad l
.nh
.SH NAME
funcs.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'protos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBstring_size\fP (const char *str)"
.br
.RI "Calculates string's size\&. "
.ti -1c
.RI "\fBaction_status\fP \fBmy_getline\fP (char **str)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A file to store basic string functions (for now at least) 
.SH "Function Documentation"
.PP 
.SS "\fBaction_status\fP my_getline (char ** str)"

.PP
.nf
\brief Reads line from stdin
\param str - pointer to string's first element
\return OK - string read, all ok
\return MEM_LIM - program ran out of free memory

.fi
.PP
 Also dynamically changes string's size to match the input 
.br
 
.SS "unsigned int string_size (const char * str)"

.PP
Calculates string's size\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP - pointer to string's first element 
.RE
.PP
\fBReturns\fP
.RS 4
Full string size including '\\0' 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for String operations\&.com from the source code\&.
