.TH "main.cpp" 3 "Thu Sep 1 2022" "Version 2" "String functions" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'protos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
.nf
\brief Will contain some ways to interact with functions
\param argc - count of com line args
\param argv - array of com line args
\return 0 - if OK

.fi
.PP
 Now will hold a program that will sort an array of strings also called 'Onegin'
.PP
first it reads strings from file with name onegin second it sorts them and prints them 
.SH "Author"
.PP 
Generated automatically by Doxygen for String functions from the source code\&.
