.TH "protos.h" 3 "Sun Aug 28 2022" "Version 2" "String operations.com" \" -*- nroff -*-
.ad l
.nh
.SH NAME
protos.h
.SH SYNOPSIS
.br
.PP
\fC#include <TXlib\&.h>\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBaction_status\fP { \fBOK\fP = 1, \fBMEM_ERR\fP = 0 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBaction_status\fP \fBmy_getline\fP (char **string_to_input_to)"
.br
.ti -1c
.RI "unsigned int \fBstring_size\fP (const char *string_to_measure)"
.br
.RI "Calculates string's size\&. "
.ti -1c
.RI "\fBaction_status\fP \fBmy_strncpy\fP (char **from, char **to, unsigned int n)"
.br
.ti -1c
.RI "\fBaction_status\fP \fBmy_strcpy\fP (char *from, char *to)"
.br
.RI "A simply strcpy function\&. "
.ti -1c
.RI "\fBaction_status\fP \fBmy_smart_strcpy\fP (char **from, char **to)"
.br
.ti -1c
.RI "void \fBunit_test\fP ()"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBaction_status\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOK \fP\fP
.TP
\fB\fIMEM_ERR \fP\fP
.SH "Function Documentation"
.PP 
.SS "\fBaction_status\fP my_getline (char ** str)"

.PP
.nf
\brief Reads line from stdin
\param str - pointer to string's first element
\return OK - string read, all ok
\return MEM_LIM - program ran out of free memory

.fi
.PP
 Also dynamically changes string's size to match the input 
.br
 
.SS "\fBaction_status\fP my_smart_strcpy (char ** from, char ** to)"

.SS "\fBaction_status\fP my_strcpy (char * from, char * to)"

.PP
A simply strcpy function\&. 
.PP
\fBParameters\fP
.RS 4
\fIchar*\fP from - string to copy from 
.br
\fIchar*\fP to - string to copy to 
.RE
.PP
\fBReturns\fP
.RS 4
OK in all cases except when MEM_LIM 
.PP
MEM_ERR if one of the pointers is NULL
.RE
.PP
A simple function that copies c-string from to c-string to without minding the sizes of both Actually may cause segmentation fault if used wrong 
.SS "\fBaction_status\fP my_strncpy (char ** from, char ** to, unsigned int n)"

.SS "unsigned int string_size (const char * str)"

.PP
Calculates string's size\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP - pointer to string's first element 
.RE
.PP
\fBReturns\fP
.RS 4
Full string size including '\\0' 
.RE
.PP

.SS "void unit_test ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for String operations\&.com from the source code\&.
