.TH "sorter.cpp" 3 "Sun Sep 4 2022" "Version 2" "String functions" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sorter.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'protos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmergesort_str\fP (char **l, char **r)"
.br
.RI "Interface to interact with mergesort_str_inside\&. Look for docs there\&. "
.ti -1c
.RI "void \fBmergesort_str_inside\fP (char **l, char **r, char **temp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void mergesort_str (char ** l, char ** r)"

.PP
Interface to interact with mergesort_str_inside\&. Look for docs there\&. 
.SS "void mergesort_str_inside (char ** l, char ** r, char ** temp)"

.PP
.nf
\brief Sorts an array of strings in right order
\param l - pointer to the beginning of an array
\param r - pointer to the element right after an array end
\param temp - temporary array used for merging

.fi
.PP
 Mergesorts through a c-string array tries not to eat memory but is bad at it also fast somehow 
.SH "Author"
.PP 
Generated automatically by Doxygen for String functions from the source code\&.
