.TH "strchr.cpp" 3 "Tue Aug 30 2022" "Version 2" "String functions" \" -*- nroff -*-
.ad l
.nh
.SH NAME
strchr.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'protos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBmy_strchr\fP (char *const src, const char ch)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* my_strchr (char *const src, const char ch)"

.PP
.nf
\brief Finds a char
\param src - string to search in
\param ch - char to search for
\return ptr to a char in string
\return NULL if there is no char in string or no string

.fi
.PP
 Finds a set char in a set string and returns a ptr to char in the string 
.SH "Author"
.PP 
Generated automatically by Doxygen for String functions from the source code\&.
