.TH "strcpy.cpp" 3 "Sun Aug 28 2022" "Version 2" "String operations.com" \" -*- nroff -*-
.ad l
.nh
.SH NAME
strcpy.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'protos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBaction_status\fP \fBmy_strcpy\fP (char *from, char *to)"
.br
.RI "A simply strcpy function\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBaction_status\fP my_strcpy (char * from, char * to)"

.PP
A simply strcpy function\&. 
.PP
\fBParameters\fP
.RS 4
\fIchar*\fP from - string to copy from 
.br
\fIchar*\fP to - string to copy to 
.RE
.PP
\fBReturns\fP
.RS 4
OK in all cases except when MEM_LIM 
.PP
MEM_ERR if one of the pointers is NULL
.RE
.PP
A simple function that copies c-string from to c-string to without minding the sizes of both Actually may cause segmentation fault if used wrong 
.SH "Author"
.PP 
Generated automatically by Doxygen for String operations\&.com from the source code\&.
