.TH "strdup.cpp" 3 "Tue Aug 30 2022" "Version 2" "String functions" \" -*- nroff -*-
.ad l
.nh
.SH NAME
strdup.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'protos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBmy_strdup\fP (const char *src)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* my_strdup (const char * src)"

.PP
.nf
\brief Copies a string to heap
\param src - string to copy
\return ptr to an allocated memory

.fi
.PP
 Returns a pointer to a newly allocated memory that contains a copy of a string passed into it 
.SH "Author"
.PP 
Generated automatically by Doxygen for String functions from the source code\&.
