.TH "strlen.cpp" 3 "Tue Aug 30 2022" "Version 2" "String functions" \" -*- nroff -*-
.ad l
.nh
.SH NAME
strlen.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'protos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBmy_strlen\fP (const char *str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "unsigned int my_strlen (const char * str)"

.PP
.nf
\brief Returns string length
\param str - string to calculate len of
\return -1 - if str is NULL
\return anything >=0 - string's len

.fi
.PP
 Calculates string length\&. Nothing more to say 
.SH "Author"
.PP 
Generated automatically by Doxygen for String functions from the source code\&.
