.TH "unit_test.cpp" 3 "Sun Aug 28 2022" "Version 2" "String operations.com" \" -*- nroff -*-
.ad l
.nh
.SH NAME
unit_test.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'protos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBunit_test\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void unit_test ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for String operations\&.com from the source code\&.
