.TH "unit_test.cpp" 3 "Sun Sep 4 2022" "Version 2" "String functions" \" -*- nroff -*-
.ad l
.nh
.SH NAME
unit_test.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'protos\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBunit_test\fP ()"
.br
.RI "Tests correctness of work of some functions\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void unit_test ()"

.PP
Tests correctness of work of some functions\&. < Test of fgets
.PP
< EOTest of fgets
.PP
< Test of fputs
.PP
< EOTest of fputs
.PP
< Test of strcat
.PP
< EOTest of strcat
.PP
< Test of strncat
.PP
< EOTest of strncat
.PP
< Test of strchr
.PP
< EOTest of strchr
.PP
< Test of strdup
.PP
< EOTest of strdup
.PP
< Test of strlen
.PP
< EOTest52
.PP
< Test of strcpy
.PP
< EOTest of strcpy
.PP
< Test of strncpy
.PP
< EOTest of strncpy
.PP
< Test of smart_strcpy
.PP
< EOTest of smart_strcpy
.SH "Author"
.PP 
Generated automatically by Doxygen for String functions from the source code\&.
